; XIAO STM32C5 headless LKM MS3506/MS3008 gimbal controller

[env:seeed-xiao-stm32c5]
platform = SeeedStudio
board = seeed-xiao-stm32c5
framework = zephyr
build_src_filter = +<*.c> -<round_ui.c> -<touch.c>
